// *****************************************************************************************************************
// Configuration for different microcontrollers (MUC) to ensure compatibility with the code:
// - Defines the clock speed, timers, and interrupts for each MUC.
// - Configures I/O pins for data, clocks, and switches according to the requirements.
// - Enables pull-up resistors on input pins where needed.
// - Manages external interrupts and LED outputs for system feedback.
// - Ensures the setup is compatible with various microcontroller models (e.g., ATmega328, ATtiny series, etc.)
// *****************************************************************************************************************

//******************************************************************************************************************
// Configuring the clock speed and associated registers. The formula for calculating 
// the clock frequency is F_CPU / (TCCR0B |= (1<<CS00)) * (OCR0A = 159 +1) = 16000000 / (0 * (160)) = 100KHz
//******************************************************************************************************************

//******************************************************************************************************************

// Example: DDRB &= ~(1<<DDB0);

// Define the pins as inputs.

// Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), and then inverting it.
// The bitwise AND operation (&=) updates the register DDRB by clearing the DDB0 bit (setting it to 0) 
// without affecting the other bits. 
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask 
// (1<<DDB0) = b00000001, and then inverts it, which results in b11111110. The AND operation with DDRB clears DDB0.
// 
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    ~(b00000001) = b11111110  // Mask generated by shifting and inverting the bit
// After:   DDRB = b11111110  // The DDB0 bit is cleared (set to 0), while other bits remain unchanged
//******************************************************************************************************************

//******************************************************************************************************************

// Example: DDRB |= (1<<DDB0);

// Enable pull-ups and set high on the pins.

// Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), 
// and then apply a bitwise OR operation to set DDB0 to 1 (configure pin PB0 as an output).
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask 
// (1<<DDB0) = b00000001. The OR operation with DDRB sets the DDB0 bit to 1, leaving other bits unchanged.
// 
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    (1<<DDB0) = b00000001  // Mask generated by shifting the bit 1 to the left to position DDB0
// After:   DDRB = b11111111  // The DDB0 bit is set to 1, configuring pin PB0 as an output
//******************************************************************************************************************

//******************************************************************************************************************

// Example: (!!(PIND & (1<<PIND6)));

// Read the state of the input pins with Boolean Normalization.

// Create a mask by shifting the bit 1 to the left by PIND6's position (bit 6),
// then apply a bitwise AND operation to read the state of the PIND6 pin.
// Finally, apply a double logical NOT (!!) to normalize the result to 0 or 1.
// The result will be 1 (true) if the PIND6 pin is high (1), and 0 (false) if the PIND6 pin is low (0).
//
// For instance, if PIND = b01000000 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PIND6) = b01000000. The AND operation isolates the bit, and !! converts it to a pure boolean 1.
//
// Before: PIND = b01000000 // Initial value (PIN 6 is HIGH)
// Mask: (1<<PIND6) = b01000000 // Mask for bit 6
// Step 1: PIND & Mask = b01000000 (Value: 64)
// Step 2: !64 = 0
// Step 3: !0 = 1 // Final Normalized Result
// 
//******************************************************************************************************************

//******************************************************************************************************************

// Example: PORTB |= (1<<PB0);

// Set the state of an output pin to HIGH (Equivalent of Arduino digitalWrite(8, HIGH);).

// Create a mask by shifting the bit 1 to the left by PB0's position (bit 0),
// and then apply a bitwise OR operation to force the PB0 pin to a high state.
// This operation modifies only the target bit without affecting the others in the register.
//
// For instance, if PORTB = b10101010 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PB0) = b00000001. The OR operation between PORTB and the mask ensures the 0th bit becomes 1 (high).
//
// Before: PORTB = b10101010 // Initial value of PORTB (register controlling output pin states)
// Mask: (1<<PB0) = b00000001 // Mask generated by shifting the bit 1 to the left to position PB0
// Operation: PORTB | b00000001 = b10101011 // The 0th bit is set to 1 (high)
//
//******************************************************************************************************************

//******************************************************************************************************************

// Example: PORTB &= ~(1<<PB0);

// Set the state of an output pin to LOW (Equivalent of Arduino digitalWrite(8, LOW);).

// Create a mask by shifting the bit 1 to the left by PB0's position (bit 0).
// The mask is then inverted at the bit level (binary NOT) to create a clearing mask (all bits are 1 except the target bit, which is 0).
// Finally, a bitwise AND operation is applied to force the PB0 pin to a low state.
// This operation modifies only the target bit without affecting the others in the register.
//
// For instance, if PORTB = b10101011 (binary value), the generated mask is (1<<PB0) = b00000001.
// Inverting (NOT) the mask yields ~(1<<PB0) = b11111110.
// The bitwise AND operation between PORTB and the clearing mask ensures the 0th bit becomes 0 (low).
//
// Before: PORTB = b10101011 // Initial value of PORTB (register controlling output pin states)
// Mask: ~(1<<PB0) = b11111110 // Generated clearing mask
// Operation: PORTB & b11111110 = b10101010 // The 0th bit is set to 0 (low)
//
//******************************************************************************************************************

//******************************************************************************************************************

// Enables (masks in) the Hardware External Interrupt 0 (INT0).

// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, CHANGE);
//
// Example: EIMSK |= (1<<INT0);
//
// Creates a mask by shifting the bit 1 to the left to the position of the INT0 bit.
// A bitwise OR operation is then applied to the EIMSK (External Interrupt Mask Register) register to set that specific bit to 1.
// Enabling this bit tells the microcontroller to start listening for signals on the physical pin associated with INT0 (typically Pin D2 on the Arduino UNO/Nano).
//
// For instance, if EIMSK = b00000000 (all interrupts disabled), the generated mask is (1<<INT0) = b00000001 (assuming INT0 is defined as 0).
// The bitwise OR operation ensures the INT0 bit is set to 1, without affecting the other interrupts.
//
// Before: EIMSK = b00000000 // All interrupts disabled
// Mask: (1<<INT0) = b00000001 // Generated enable mask
// Operation: EIMSK | b00000001 = b00000001 // The INT0 interrupt is now enabled
//
//******************************************************************************************************************

//******************************************************************************************************************

// Disables (masks out) the Hardware External Interrupt 0 (INT0).

// Equivalent to the Arduino function: detachInterrupt(digitalPinToInterrupt(2));
//
// Example: EIMSK &= ~(1<<INT0);
//
// Creates a mask by shifting the bit 1 to the left by the position of the INT0 bit.
// The mask is then inverted at the bit level (binary NOT) to create a clearing mask (all bits are 1 except the target bit, which is 0).
// A bitwise AND operation is applied to the EIMSK (External Interrupt Mask Register) register to force that specific bit to 0.
// Disabling this bit tells the microcontroller to stop listening for signals on the physical pin associated with INT0 (typically Pin D2 on the Arduino UNO/Nano).
//
// For instance, if EIMSK = b00000001 (INT0 interrupt is enabled), the generated mask is (1<<INT0) = b00000001.
// Inverting (NOT) the mask yields ~(1<<INT0) = b11111110.
// The bitwise AND operation between EIMSK and the clearing mask ensures the INT0 bit becomes 0 (disabled).
//
// Before: EIMSK = b00000001 // INT0 interrupt is enabled
// Mask: ~(1<<INT0) = b11111110 // Generated disable mask
// Operation: EIMSK & b11111110 = b00000000 // The INT0 interrupt is now disabled
//
//******************************************************************************************************************

//******************************************************************************************************************

// Configures the external interrupt 0 (INT0) to trigger on a RISING edge (when the signal goes from LOW to HIGH).

// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, RISING);
//
// Example: EICRA |= (1<<ISC01)|(1<<ISC00);
//
// This operation sets both the ISC01 and ISC00 bits within the EICRA register (External Interrupt Control Register A) to 1.
// These two bits together form a 2-bit control field that determines how the INT0 pin should react to changes in voltage.
// The specific combination of ISC01=1 and ISC00=1 defines the "RISING Edge" mode according to the AVR datasheet.
//
// EICRA register (simplified view of relevant bits):
// | Bit 7 | Bit 6 | Bit 5 | Bit 4 | Bit 3 | Bit 2 | Bit 1 (ISC01) | Bit 0 (ISC00) |
// | :---: | :---: | :---: | :---: | :---: | :---: | :-----------: | :-----------: |
// | | | | | | | 1 | 1 |
//
// The bitwise OR (|=) ensures that only these two specific bits are modified, leaving all other interrupt configurations unchanged.
//
// Before: EICRA = b00000000 // Default state (usually LOW level triggers)
// Mask: (1<<ISC01)|(1<<ISC00) = b00000011 // Mask to set both bits 0 and 1
// Operation: EICRA | b00000011 = b00000011 // INT0 is now configured for RISING edge triggers
//
//******************************************************************************************************************

//******************************************************************************************************************

// Configures the external interrupt 0 (INT0) to trigger on a FALLING edge (when the signal goes from HIGH to LOW).
// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, FALLING);
//
// Example: (EICRA = (EICRA & ~(1<<ISC00)) | (1<<ISC01));
//
// This combined operation first ensures that the ISC00 bit is cleared to 0 (& ~(1<<ISC00)), and then sets the ISC01 bit to 1 (| (1<<ISC01)).
// These two bits together form a 2-bit control field that determines how the INT0 pin should react to changes in voltage.
// The specific combination of ISC01=1 and ISC00=0 defines the "FALLING Edge" mode according to the AVR datasheet.
//
// EICRA register (simplified view of relevant bits):
// | Bit 7 | Bit 6 | Bit 5 | Bit 4 | Bit 3 | Bit 2 | Bit 1 (ISC01) | Bit 0 (ISC00) |
// | :---: | :---: | :---: | :---: | :---: | :---: | :-----------: | :-----------: |
// | | | | | | | 1 | 0 |
//
// The complex bitwise operation ensures that we set a specific 2-bit value while leaving other unrelated bits in the EICRA register unchanged.
//
// Operation Breakdown:
// 1. Clear ISC00 bit: EICRA & ~(1<<ISC00)
// 2. Set ISC01 bit: ... | (1<<ISC01)
// Before:  EICRA = b00000011  // Initial value with ISC01 = 1 and ISC00 = 1 (rising edge trigger for INT0)
// Operation: EICRA & ~(1<<ISC00) clears ISC00 bit (sets it to 0) while keeping ISC01 at 1. Then OR operation with (1<<ISC01) ensures ISC01 stays 1.
// After:   EICRA = b00000010  // The bit ISC00 is now cleared, configuring INT0 to trigger on the falling edge.
//
//******************************************************************************************************************

//******************************************************************************************************************
// Identifier for the Interrupt Vector for External Interrupt 0 (INT0).
//
// Example: ISR(INT0_vect) { ... }
//
// This is not an executable instruction but a symbolic name (an alias or macro) defined in the AVR-GCC header files
// (<avr/interrupt.h>). It points to the specific memory address in the microcontroller's flash memory where the
// Interrupt Service Routine (ISR) for the INT0 event must reside.
//
// When you write ISR(INT0_vect) { ... }, you are telling the compiler: "Place this block of code at the
// location the CPU jumps to when a hardware signal is detected on the INT0 pin."
//
// In Arduino code, this identifier is hidden from the user and managed internally by the
// attachInterrupt() function.
//
//******************************************************************************************************************

#pragma once

#ifdef ATmega328_168
  /*------------------------------------------------------------------------------------------------
  * FUNCTION    : optimizePeripherals()
  * 
  * DESCRIPTION : 
  *    Minimizes power consumption and internal noise by disabling unused hardware modules.
  *    Performs a hard shutdown of peripherals to reduce current leakage and CPU jitter.
  * 
  *    1. ANALOG SHUTDOWN: Disables ADC and Analog Comparator to prevent parasitic drain.
  *    2. BUFFER DISABLE: Disconnects digital input buffers on analog pins (A0-A5).
  *    3. CLOCK GATING (PRR): Shuts down clocks to TWI, SPI, and all Timers (0, 1, 2).
  *    4. UART MAINTENANCE: Keeps PRUSART0 active to allow Serial communication.
  ------------------------------------------------------------------------------------------------*/
  static inline void OptimizePeripherals(void) {
    // 1. Disable Interrupts during setup
    cli();

    // 2. Analog Modules Shutdown (Critical for Power)
    ADCSRA &= ~(1 << ADEN); // Disable ADC
    ACSR   |= (1 << ACD);   // Disable Analog Comparator

    // 3. Digital Input Disable (Set bits to 1 to DISABLE)
    // Disconnects digital buffers on analog pins to stop leakage
    DIDR0 = 0x3F; // Pins A0 to A5

    // 4. GPIO Strategy (Unused pins to Pull-up)
    // PORTx = 0xFF (Pull-ups) | DDRx = 0x00 (Inputs)
    PORTC |= 0xFF;

    // 5. Power Reduction Register (PRR)
    // We KEEP PRUSART0 (UART) and shut down EVERYTHING else.
    // _delay_ms() will still work (it's cycle-based, not timer-based).
    PRR = (1 << PRTWI)  | // I2C Off
          (1 << PRSPI)  | // SPI Off
          (1 << PRTIM0) | // Timer 0 Off (millis/delay Arduino Off)
          (1 << PRTIM1) | // Timer 1 Off
          (1 << PRTIM2) | // Timer 2 Off
          (1 << PRADC);   // ADC Clock Off

    // 6. Double Security for Timer 0
    TCCR0B = 0;
    TIMSK0 = 0;

    // 7. Restart interrupts if UART uses them (RX/TX ISR)
    //sei();
  }

  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Main pin configuration

  // Define the main pins as inputs
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)  // Set DDRB register to configure PINB0 as input
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)  // Set DDRB register to configure PINB1 as input
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)  // Set DDRB register to configure PINB6 as input
  #define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)  // Set DDRB register to configure PINB7 as input

  // Configure lines as outputs (for injection/override)
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)  // Set DDRB register to configure PINB0 as output
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)  // Set DDRB register to configure PINB1 as output

  // Bus line state control (Set High / Clear Low)
  #define PIN_DATA_SET PORTB |= (1 << PB0)  // Set PORTB register to make PINB0 high (enable pull-up))
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)  // Set PORTB register to make PINB0 low
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)  // Set PORTB register to make PINB1 low

  // Direct Register Reading (High-speed polling)
  #define PIN_SQCK_READ (!!(PIND & (1 << PIND6)))  // Check if the value of PIND6 is high (1)
  #define PIN_SUBQ_READ (!!(PIND & (1 << PIND7)))  // Check if the value of PIND7 is high (1)
  #define PIN_WFCK_READ (!!(PINB & (1 << PINB1)))  // Check if the value of PIND1 is high (1)

  // --- Status Indication (LED) ---
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB |= (1 << DDB5)  // Configure PINB5 as output (for LED)
    #define PIN_LED_ON    PORTB |= (1 << PB5)  // Set PINB5 high (turn on LED)
    #define PIN_LED_OFF   PORTB &= ~(1 << PB5)  // Set PINB5 low (turn off LED)
  #endif

  // --- BIOS Patching Configuration ---
  #if defined(SCPH_102)       || \
      defined(SCPH_100)       || \
      defined(SCPH_7500_9000) || \
      defined(SCPH_7000)      || \
      defined(SCPH_3500_5500) || \
      defined(SCPH_3000)      || \
      defined(SCPH_1000)

    // Address (AX) and Data (DX) lines for BIOS override
    #define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
    #define PIN_DX_SET PORTD |= (1 << PD4)
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)

    // Blocking wait macros for AX synchronization
    #define WAIT_AX_RISING    (!(PIND & (1 << PIND2)))  // Wait for pulse start (Blocking until Rising Edge)
    #define WAIT_AX_FALLING   (PIND & (1 << PIND2))     // Wait for pulse end (Blocking until Falling Edge)
    #define PIN_AX_READ   (!!(PIND & (1 << PIND2))) 

    // Hardware Interrupt (INT0) for AX pulse counting
    #define PIN_AX_INTERRUPT_ENABLE     EIMSK  |=  (1<<INT0)      // Enable external interrupt on INT0 (PINB2)
    #define PIN_AX_INTERRUPT_DISABLE    EIMSK  &= ~(1<<INT0)      // Disable external interrupt on INT0
    #define PIN_AX_INTERRUPT_RISING     EICRA  |=  (1<<ISC01)|(1<<ISC00)                  // Configure INT0 for rising edge trigger
    #define PIN_AX_INTERRUPT_VECTOR     INT0_vect               // Interrupt vector for INT0 (external interrupt)

    // Secondary Address line (AY) for multi-stage patching (INT1)
    #if defined(SCPH_3000) || \
        defined(SCPH_1000)
      #define PIN_AY_INPUT       DDRD &= ~(1 << DDD3)  // Set DDRD register to configure PIND3 as input
      #define WAIT_AY_RISING     (!(PIND & (1 << PIND3))) 
      #define WAIT_AY_FALLING    (PIND & (1 << PIND3))
      
      #define PIN_AY_INTERRUPT_ENABLE     EIMSK  |=  (1<<INT1)      // Enable external interrupt on INT1 (PINB3)
      #define PIN_AY_INTERRUPT_DISABLE    EIMSK  &= ~(1<<INT1)      // Disable external interrupt on INT1
      #define PIN_AY_INTERRUPT_RISING     EICRA  |=  (1<<ISC11)|(1<<ISC10)                  // Configure INT1 for rising edge trigger
      #define PIN_AY_INTERRUPT_VECTOR     INT1_vect              // Interrupt vector for INT1 (external interrupt)
    #endif

     // Hardware Bypass Switch (On-the-fly deactivation)
    #if defined(SCPH_7000)
      #define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)  // Configure PIND5 as input for switch
      #define PIN_SWITCH_SET   PORTD |= (1 << PD5)     // Set PIND5 high (enable pull-up)
      #define PIN_SWITCH_READ (!!(PIND & (1 << PIND5)))  // Read the state of PIND5 (switch input)
    #endif

  #endif

  // #if defined(PSNEE_DEBUG_SERIAL_MONITOR)
  //   #define DEBUG_PRINT(x)     Serial.print(x)
  //   #define DEBUG_PRINTHEX(x)  Serial.print(x, HEX)
  //   #define DEBUG_PRINTLN(x)   Serial.println(x)
  //   #define DEBUG_FLUSH        Serial.flush()
  // #endif

#endif


#ifdef ATmega32U4_16U4

  static inline void OptimizePeripherals(void) {
      // 1. Global Interrupt Disable during hardware reconfiguration
      cli();

      // 2. Analog Front-End Shutdown
      ADCSRA &= ~(1 << ADEN); // Disable ADC
      ACSR   |= (1 << ACD);   // Disable Analog Comparator

      // 3. Digital Input Buffer Disable (DIDR0 & DIDR2)
      // 32U4 has more analog channels (ADC0-ADC7 and ADC8-ADC13)
      DIDR0 = 0xFF; // Disable digital buffers on F0-F7
      DIDR2 = 0x3F; // Disable digital buffers on D4, D6, D7, B4, B5, B6

      // 4. GPIO Strategy (Unused pins to Pull-up)
      // On 32U4, Port C is small (only PC6/PC7). Adjusting to cover most unused pins.
      PORTC |= 0xFF;
      PORTE |= 0xFF; // Extra port on 32U4

      // 5. Power Reduction Registers (PRR0 & PRR1)
      // PRR0 handles TWI, SPI, Timers 0, 1 and ADC.
      PRR0 = (1 << PRTWI)  | // I2C Off
            (1 << PRSPI)  | // SPI Off
            (1 << PRTIM0) | // Timer 0 Off
            (1 << PRTIM1) | // Timer 1 Off
            (1 << PRADC);   // ADC Clock Off
      
      // PRR1 handles Timer 3, Timer 4 and USB.
      // We KEEP PRUSART1 (Serial1) and PRUSB active for communication.
      PRR1 = (1 << PRTIM3) | // Timer 3 Off
            (1 << PRTIM4);  // Timer 4 Off (High speed timer)

      // 6. Double Security for Timer 0 (Redundancy)
      TCCR0B = 0;
      TIMSK0 = 0;

      // 7. Note: USB/Serial1 remain functional unless PRUSB/PRUSART1 are set.
  }

  //#define F_CPU 16000000L


  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>


  // --- Main Bus Interface (CD-ROM Controller) ---

  // Define the main pins as inputs
  #define PIN_DATA_INPUT  DDRB &= ~(1 << DDB4) // DATA line (PB4)
  #define PIN_WFCK_INPUT  DDRB &= ~(1 << DDB5) // WFCK / GATE line (PB5)
  #define PIN_SQCK_INPUT  DDRD &= ~(1 << DDD7) // SQCK Clock (PD7)
  #define PIN_SUBQ_INPUT  DDRE &= ~(1 << DDE6) // SUBQ Data (PE6)

  // Configure lines as outputs (for injection/override)
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB4)
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB5)

  // Bus line state control (Set High / Clear Low)
  #define PIN_DATA_SET    PORTB |=  (1 << PB4) // Enable pull-up or drive HIGH
  #define PIN_DATA_CLEAR  PORTB &= ~(1 << PB4) // Drive line LOW
  #define PIN_WFCK_CLEAR  PORTB &= ~(1 << PB5) // Drive line LOW

  // Direct Register Reading (High-speed polling)
  #define PIN_SQCK_READ   (PIND & (1 << PIND7))
  #define PIN_SUBQ_READ   (PINE & (1 << PINE6))
  #define PIN_WFCK_READ   (PINB & (1 << PINB5))

  // --- Status Indication (LED) ---
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB  |=  (1 << DDB6) // LED on PB6
    #define PIN_LED_ON     PORTB |=  (1 << PB6)
    #define PIN_LED_OFF    PORTB &= ~(1 << PB6)
  #endif

  // --- BIOS Patching Configuration (32U4 Mapping) ---
  #if defined(SCPH_102) || defined(SCPH_102_legacy) || defined(SCPH_100) || \
      defined(SCPH_7000_9000) || defined(SCPH_5500) || defined(SCPH_3500_5000) || \
      defined(SCPH_3000) || defined(SCPH_1000)

    // Address (AX / AY) and Data (DX) lines for BIOS override
    #define PIN_AX_INPUT    DDRD &= ~(1 << DDD1) // AX on PD1 (INT1)
    #define PIN_AY_INPUT    DDRD &= ~(1 << DDD0) // AY on PD0 (INT0)
    #define PIN_DX_INPUT    DDRD &= ~(1 << DDD4) // DX on PD4
    
    #define PIN_DX_OUTPUT   DDRD |=  (1 << DDD4)
    #define PIN_DX_SET      PORTD |=  (1 << PD4)
    #define PIN_DX_CLEAR    PORTD &= ~(1 << PD4)

    // Blocking wait macros for synchronization
    #define WAIT_AX_RISING  (!(PIND & (1 << PIND1))) // Wait for pulse start
    #define WAIT_AX_FALLING  (PIND & (1 << PIND1))   // Wait for pulse end
    #define PIN_AX_READ      (PIND & (1 << PIND1))

    // Hardware Interrupt (INT1) for AX pulse counting
    #define PIN_AX_INTERRUPT_ENABLE   EIMSK  |=  (1 << INT1)
    #define PIN_AX_INTERRUPT_DISABLE  EIMSK  &= ~(1 << INT1)
    #define PIN_AX_INTERRUPT_RISING   EICRA  |=  (1 << ISC11) | (1 << ISC10)
    #define PIN_AX_INTERRUPT_VECTOR   INT1_vect

    // Secondary Address line (AY) for multi-stage patching (INT0)
    #if defined(SCPH_3000) || defined(SCPH_1000)
      #define PIN_AY_READ      (PIND & (1 << PIND0))
      #define WAIT_AY_RISING   (!(PIND & (1 << PIND0)))
      #define WAIT_AY_FALLING   (PIND & (1 << PIND0))
      
      #define PIN_AY_INTERRUPT_ENABLE   EIMSK  |=  (1 << INT0)
      #define PIN_AY_INTERRUPT_DISABLE  EIMSK  &= ~(1 << INT0)
      #define PIN_AY_INTERRUPT_RISING   EICRA  |=  (1 << ISC01) | (1 << ISC00)
      #define PIN_AY_INTERRUPT_VECTOR   INT0_vect
    #endif

    // Hardware Bypass Switch (On-the-fly deactivation)
    #ifdef (SCPH_7000)
      #define PIN_SWITCH_INPUT DDRC  &= ~(1 << DDC6) // Bypass on PC6
      #define PIN_SWITCH_SET   PORTC |=  (1 << PC6)  // Enable pull-up
      #define PIN_SWITCH_READ  (PINC & (1 << PINC6))
    #endif
  #endif
#endif

  // // Globale interrupt seting
  // #define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
  // #define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)



  // // Handling the main pins

  // // Main pins
  // #define PIN_DATA_INPUT DDRB &= ~(1 << DDB4)
  // #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB5)
  // #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD7)
  // #define PIN_SUBQ_INPUT DDRE &= ~(1 << DDE6)

  // #define PIN_DATA_OUTPUT DDRB |= (1 << DDB4)
  // #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB5)

  // // Define pull-ups and set high at the main pin
  // #define PIN_DATA_SET PORTB |= (1 << PB4)
  // // Define pull-ups set down at the main pin
  // #define PIN_DATA_CLEAR PORTB &= ~(1 << PB4)
  // #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB5)
  // // Read the main pins
  // #define PIN_SQCK_READ (PIND & (1 << PIND7))
  // #define PIN_SUBQ_READ (PINE & (1 << PINE6))
  // #define PIN_WFCK_READ (PINB & (1 << PINB5))

  // // Handling and use of the LED pin
  // #ifdef LED_RUN
  //   #define PIN_LED_OUTPUT DDRB |= (1 << DDB6)
  //   #define PIN_LED_ON PORTB |= (1 << PB6)
  //   #define PIN_LED_OFF PORTB &= ~(1 << PB6)
  // #endif

  // // Handling the BIOS patch
  // #if defined(SCPH_102) || defined(SCPH_102_legacy) || defined(SCPH_100) || defined(SCPH_7000_9000) || defined(SCPH_5500) || defined(SCPH_3500_5000) || defined(SCPH_3000) || defined(SCPH_1000)
  // // Pins input
  //   #define PIN_AX_INPUT DDRD &= ~(1 << DDD1)
  //   #define PIN_AY_INPUT DDRD &= ~(1 << DDD0)
  //   #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
  //   // Pin output
  //   #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
  //   // Define pull-ups set high
  //   #define PIN_DX_SET PORTD |= (1 << PD4)
  //   // Define pull-ups set down
  //   #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
  //   // Read pins for BIOS patch
  //   #define PIN_AX_READ (PIND & (1 << PIND1))
  //   #define PIN_AY_READ (PIND & (1 << PIND0))
  //   // Handling and reading the switch pin for patch BIOS
  //   #ifdef PATCH_SWITCH
  //     #define PIN_SWITCH_INPUT DDRC &= ~(1 << DDC6)
  //     #define PIN_SWITCH_SET PORTC |= (1 << PC6)
  //     #define PIN_SWITCH_READ (PINC & (1 << PINC6))
  //   #endif

  //   // BIOS timer clear
  //   #define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

  //   // Handling the external interrupt
  //   #define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT1)
  //   #define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT0)

  //   #define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)
  //   #define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)

  //   #define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)
  //   #define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)

  //   #define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))
  //   #define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))

  //   #define PIN_AX_INTERRUPT_VECTOR INT1_vect
  //   #define PIN_AY_INTERRUPT_VECTOR INT0_vect

  // #endif

  //#endif

#ifdef ATtiny85_45_25

  static inline void OptimizePeripherals(void) {
      // 1. Global Interrupt Disable during reconfiguration
      cli();

      // 2. Analog Modules Shutdown
      ADCSRA &= ~(1 << ADEN); // Disable ADC
      ACSR   |=  (1 << ACD);  // Disable Analog Comparator

      // 3. Digital Input Buffer Disable (DIDR0)
      // Disconnects digital buffers on PB0-PB5 to prevent leakage
      DIDR0 = 0x3F; 

      // 4. Power Reduction Register (PRR)
      // Shuts down clocks to ADC and Timer 0.
      // We KEEP USI or Timer 1 if required for specific logic.
      PRR |= (1 << PRADC) | (1 << PRTIM0);

      // 5. Timer 0 Specific Shutdown (Hardware Redundancy)
      TCCR0B = 0;
      TIMSK &= ~(1 << OCIE0A); // Disable Timer 0 interrupts
  }


  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>


  // --- Main Bus Interface (CD-ROM Controller) ---

  // Define the main pins as inputs
  #define PIN_DATA_INPUT  DDRB &= ~(1 << DDB2) // DATA line (PB2)
  #define PIN_WFCK_INPUT  DDRB &= ~(1 << DDB4) // WFCK / GATE line (PB4)
  #define PIN_SQCK_INPUT  DDRB &= ~(1 << DDB0) // SQCK Clock (PB0)
  #define PIN_SUBQ_INPUT  DDRB &= ~(1 << DDB1) // SUBQ Data (PB1)

  // Configure lines as outputs (for injection/override)
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB2)
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB4)

  // Bus line state control (Set High / Clear Low)
  #define PIN_DATA_SET    PORTB |=  (1 << PB2) // Enable pull-up or drive HIGH
  #define PIN_DATA_CLEAR  PORTB &= ~(1 << PB2) // Drive line LOW
  #define PIN_WFCK_CLEAR  PORTB &= ~(1 << PB4) // Drive line LOW

  // Direct Register Reading (High-speed polling)
  #define PIN_SQCK_READ   (PINB & (1 << PINB0))
  #define PIN_SUBQ_READ   (PINB & (1 << PINB1))
  #define PIN_WFCK_READ   (PINB & (1 << PINB4))

  // Timer Interrupt Management
  #define TIMER_INTERRUPT_ENABLE  TIMSK |=  (1 << OCIE0A)
  #define TIMER_INTERRUPT_DISABLE TIMSK &= ~(1 << OCIE0A)

  // --- Status Indication (LED) ---
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB  |=  (1 << DDB3) // LED on PB3
    #define PIN_LED_ON     PORTB |=  (1 << PB3)
    #define PIN_LED_OFF    PORTB &= ~(1 << PB3)
  #endif

  // --- Debug Serial (Software Serial) ---
  #if defined(PSNEE_DEBUG_SERIAL_MONITOR)
    #include <SoftwareSerial.h>
    // SoftwareSerial(RX, TX): RX set to -1 (disabled), TX on PB3
    // Note: Resource conflict if LED_RUN is also on PB3
    SoftwareSerial mySerial(-1, 3); 
    #define PIN_TXD_OUTPUT DDRB |= (1 << DDB3)
  #endif

  // --- Safety Check: BIOS Patch Compatibility ---
  #if defined(SCPH_1000)      || \
      defined(SCPH_3000)      || \
      defined(SCPH_3500_5000) || \
      defined(SCPH_5500)      || \
      defined(SCPH_7000_9000) || \
      defined(SCPH_100)       || \
      defined(SCPH_102) 
    #error "ATtiny85/45/25 architecture is not compatible with the BIOS patch feature."
  #endif
#endif
//   // Handling the main pins

//   // Main pins input
//   #define PIN_DATA_INPUT DDRB &= ~(1 << DDB2)
//   #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB4)
//   #define PIN_SQCK_INPUT DDRB &= ~(1 << DDB0)
//   #define PIN_SUBQ_INPUT DDRB &= ~(1 << DDB1)

//   // Main pin output
//   #define PIN_DATA_OUTPUT DDRB |= (1 << DDB2)
//   #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB4)

//   // Define pull-ups and set high at the main pin
//   #define PIN_DATA_SET PORTB |= (1 << PB2)

//   // Define pull-ups set down at the main pin
//   #define PIN_DATA_CLEAR PORTB &= ~(1 << PB2)
//   #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB4)

//   // Read the main pins
//   #define PIN_SQCK_READ (PINB & (1 << PINB0))
//   #define PIN_SUBQ_READ (PINB & (1 << PINB1))
//   #define PIN_WFCK_READ (PINB & (1 << PINB4))

//   #define TIMER_INTERRUPT_ENABLE TIMSK |= (1 << OCIE0A)
//   #define TIMER_INTERRUPT_DISABLE TIMSK &= ~(1 << OCIE0A)

//   // Handling and use of the LED pin
//   #ifdef LED_RUN
//     #define PIN_LED_OUTPUT DDRB |= (1 << DDB3)
//     #define PIN_LED_ON PORTB |= (1 << PB3)
//     #define PIN_LED_OFF PORTB &= ~(1 << PB3)
//   #endif

//   #if defined(SCPH_1000) || defined(SCPH_3000) || defined(SCPH_3500_5000) || defined(SCPH_5500) || defined(SCPH_7000_9000) || defined(SCPH_100) || defined(SCPH_102_legacy) || defined(SCPH_102) 
//    #error "ATtiny85_45_25 Not compatible with BIOS patch"
//   #endif

//   #if defined(PSNEE_DEBUG_SERIAL_MONITOR)
//     #include <SoftwareSerial.h>
//     SoftwareSerial mySerial(-1, 3); // RX, TX. (RX -1 = off)
//     #define PIN_TXD_OUTPUT DDRB |= (1 << DDB3)
//     // #define DEBUG_PRINT(x)     mySerial.print(x)
//     // #define DEBUG_PRINTHEX(x)  mySerial.print(x, HEX)
//     // #define DEBUG_PRINTLN(x)   mySerial.println(x)
//     // #define DEBUG_FLUSH        mySerial.flush()
//   #endif

// #endif

// *****************************************************************************************************************
// WARNING:
// The following code  is not functional as-is.
// *****************************************************************************************************************


#ifdef ATtiny88_48

  #define F_CPU 16000000L
  #define TIMER_TCNT_CLEAR TCNT0 = 0x00            //TCNT0 - Timer/Counter Register
  #define SET_OCROA_DIV OCR0A = 159;               //OCR0A – Output Compare Register A, 0x10011111, 100KHz
  #define SET_TIMER_TCCROA TCCR0A |= (1 << CTC0);  //TCCR0A – Timer/Counter Control Register A. turn on CTC mode, CTC0
  // On ATtiny88, TCCR0B doesn't exist — clock select bits (CS01, CS00) are in TCCR0A.
  // This sets the prescaler to 1, so the timer runs at full system clock (16 MHz).
  #define SET_TIMER_TCCROB TCCR0A |= (1 << CS01) | (1 << CS00)

  #define CTC_TIMER_VECTOR TIMER0_COMPA_vect  //interrupt vector for match event, OCR0A comparison and Timer/Counter 0


  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Globale interrupt seting
  #define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
  #define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)

  // Handling the main pins

  // Main pins input
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0
  #define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)

  // Main pin output
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)  // Create a mask (1<<0) with the first bit at 1 b00000001,
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)  // |= updates the DDRB register with the OR operator and the mask, DDRB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

  // Define pull-ups and set high at the main pin
  #define PIN_DATA_SET PORTB |= (1 << PB0)  // Create a mask (1<<0) with the first bit at 1 b00000001, 
                                            // |= updates the PORTB register with the OR operator and the mask, PORTB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

  // Define pull-ups set down at the main pin
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0

  // Read the main pins
  #define PIN_SQCK_READ (PIND & (1 << PIND6))  // Create a mask (1<<6) with the six bit at 1 b00100000,
  #define PIN_SUBQ_READ (PIND & (1 << PIND7))  // compare the PINB register and the mask with the AND operator, and returns the result, PINB bxx1xxxxx AND mask b00100000 = 1
  #define PIN_WFCK_READ (PINB & (1 << PINB1))

  // Handling and use of the LED pin
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRD |= (1 << DDD0)
    #define PIN_LED_ON PORTD |= (1 << PD0)
    #define PIN_LED_OFF PORTD &= ~(1 << PD0)
  #endif

  // Handling the BIOS patch
  #if defined(SCPH_102) || defined(SCPH_100) || defined(SCPH_7000_9000) || defined(SCPH_5500) || defined(SCPH_3500_5000) || defined(SCPH_3000) || defined(SCPH_1000)
    // BIOS interrupt seting
    #define TIMER_INTERRUPT_ENABLE TIMSK0 |= (1 << OCIE0A)
    #define TIMER_INTERRUPT_DISABLE TIMSK0 &= ~(1 << OCIE0A)

    // BIOS timer clear
    #define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

    // Pins input
    #define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
    #define PIN_AY_INPUT DDRD &= ~(1 << DDD3)
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
    // Pin output
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
    // Define pull-ups set high
    #define PIN_DX_SET PORTD |= (1 << PD4)
    // Define pull-ups set down
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
    // Read pins for BIOS patch
    #define PIN_AX_READ (PIND & (1 << PIND2))
    #define PIN_AY_READ (PIND & (1 << PIND3))

    // Handling the external interrupt
    #define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT0)
    #define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT1)

    #define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)
    #define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)

    #define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)
    #define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)

    #define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))
    #define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))

    #define PIN_AX_INTERRUPT_VECTOR INT0_vect
    #define PIN_AY_INTERRUPT_VECTOR INT1_vect

    // Handling and reading the switch pin for patch BIOS
    #ifdef PATCH_SWITCH
      #define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)
      #define PIN_SWITCH_SET PORTD |= (1 << PD5)
      #define PIN_SWITCH_READ (PIND & (1 << PIND5))
    #endif
  #endif

#endif

#ifdef ATtiny214_414

//#define SET_CTRLA
#define DF_CPU 20000000L
#define TIMER_TCNT_CLEAR TCA0.SINGLE.CNT = 0x00                           //TCNT0 - Timer/Counter Register
#define SET_OCROA_DIV TCA0.SINGLE.CMP0L = 100;                            //OCR0A – Output Compare Register A, 0x10011111, 100KHz
#define SET_TIMER_TCCROA TCA0.SINGLE.CTRLB |= (1 << TCA_SINGLE_WGM0);     //TCA_SINGLE_WGMODE_FRQ_gc    //TCCR0A – Timer/Counter Control Register A. turn on CTC mode, CTC0
#define SET_TIMER_TCCROB TCA0.SINGLE.CTRLA |= (1 << TCA_SINGLE_CLKSEL0);  //TCA_SINGLE_CLKSEL_DIV1_gc//TCCR0B – Timer/Counter Control Register B,  CS00: Clock Select,  clk I/O
                                                                          //Waveform Generation Mode, Mode 2 CTC
#define CTC_TIMER_VECTOR TCA0_OVF_vect                                    //TCA0_CMP0_vect            //interrupt vector for match event, OCR0A comparison and Timer/Counter 0


#include <stdint.h>
#include <stdbool.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/sfr_defs.h>
#include <util/delay.h>

// Globale interrupt seting
#define GLOBAL_INTERRUPT_ENABLE __asm__ __volatile__("sei" ::)   //CPU.SREG   |=  (1<<7)
#define GLOBAL_INTERRUPT_DISABLE __asm__ __volatile__("cli" ::)  //CPU.SREG   &= ~(1<<7)

// Handling the main pins

// Main pins input
#define PIN_DATA_INPUT PORTA.DIR = PIN2_bm
#define PIN_WFCK_INPUT PORTA.DIR = PIN1_bm  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
#define PIN_SQCK_INPUT PORTA.DIR = PIN4_bm  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0
#define PIN_SUBQ_INPUT PORTA.DIR = PIN3_bm

// Main pin output
#define PIN_DATA_OUTPUT PORTA.DIR |= PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001,
#define PIN_WFCK_OUTPUT PORTA.DIR |= PIN1_bm  // |= updates the DDRB register with the OR operator and the mask, DDRB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

// Define pull-ups and set high at the main pin
#define PIN_DATA_SET PORTA.OUT |= PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001,
                                           // |= updates the PORTB register with the OR operator and the mask, PORTB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

// Define pull-ups set down at the main pin
#define PIN_DATA_CLEAR PORTA.OUT &= ~PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
#define PIN_WFCK_CLEAR PORTA.OUT &= ~PIN1_bm  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0

// Read the main pins
#define PIN_SQCK_READ PORTA.IN& PIN4_bm  // Create a mask (1<<6) with the six bit at 1 b00100000,
#define PIN_SUBQ_READ PORTA.IN& PIN3_bm  // compare the PINB register and the mask with the AND operator, and returns the result, PINB bxx1xxxxx AND mask b00100000 = 1
#define PIN_WFCK_READ PORTA.IN& PIN1_bm

// Handling and use of the LED pin
#define LED_RUN
#define PIN_LED_OUTPUT PORTB.DIR |= PIN2_bm
#define PIN_LED_ON PORTB.OUT |= PIN2_bm
#define PIN_LED_OFF PORTB.OUT &= ~PIN2_bm

// Handling the BIOS patch

// BIOS interrupt seting
#define TIMER_INTERRUPT_ENABLE TCA0.SPLIT.INTCTRL |= TCA_SINGLE_CMP0_bm
#define TIMER_INTERRUPT_DISABLE TCA0.SPLIT.INTCTRL &= ~TCA_SPLIT_HCMP0_bm

// BIOS timer clear
#define TIMER_TIFR_CLEAR TCA0.SPLIT.INTFLAGS = TCA_SPLIT_HCMP0_bm

// Pins input
#define PIN_AX_INPUT PORTB.DIR &= ~PIN3_bm
#define PIN_AY_INPUT PORTA.DIR &= ~PIN7_bm
#define PIN_DX_INPUT PORTA.DIR &= ~PIN6_bm
// Pin output
#define PIN_DX_OUTPUT PORTA.DIR |= PIN6_bm
// Define pull-ups set high
#define PIN_DX_SET PORTA.OUT |= PIN6_bm
// Define pull-ups set down
#define PIN_DX_CLEAR PORTA.OUT &= ~PIN6_bm
// Read pins for BIOS patch
#define PIN_AX_READ PORTB.IN& PIN3_bm
#define PIN_AY_READ PORTA.IN& PIN6_bm

// Handling the external interrupt
//#define PIN_AX_INTERRUPT_ENABLE     PORTB.PIN3CTRL  |=  (1<<INTn)
//#define PIN_AY_INTERRUPT_ENABLE     PORTA.PIN7CTRL  |=  (1<<INTn)

#define PIN_AX_INTERRUPT_DISABLE PORTB.PIN3CTRL = PORT_ISC_INTDISABLE_gc
#define PIN_AY_INTERRUPT_DISABLE PORTA.PIN7CTRL = PORT_ISC_INTDISABLE_gc

#define PIN_AX_INTERRUPT_RISING PORTB.PIN3CTRL = PORT_ISC_RISING_gc
#define PIN_AY_INTERRUPT_RISING PORTA.PIN7CTRL = PORT_ISC_RISING_gc

#define PIN_AX_INTERRUPT_FALLING PORTB.PIN3CTRL = PORT_ISC_FALLING_gc
#define PIN_AY_INTERRUPT_FALLING PORTA.PIN7CTRL = PORT_ISC_FALLING_gc

//#define PB3_INTERRUPT PORTB.INTFLAGS & PIN3_bm
//#define PA7_INTERRUPT PORTB.INTFLAGS & PIN7_bm

#define PIN_AX_INTERRUPT_VECTOR PORTB_PORT_vect
#define PIN_AY_INTERRUPT_VECTOR PORTA_PORT_vect

// Handling and reading the switch pin for patch BIOS
#define PIN_SWITCH_INPUT PORTA.DIR &= ~PIN5_bm
#define PIN_SWITCH_SET PORTA.OUT |= PIN5_bm
#define PIN_SWITCH_READ PORTA.IN& PIN5_bm

#endif

#ifdef LGT8F328P

#define F_CPU 32000000L


#include <stdint.h>
#include <stdbool.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/sfr_defs.h>
#include <util/delay.h>

// Globale interrupt seting
#define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
#define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)

// Handling the main pins

// Main pins input
#define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)
#define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)
#define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)
#define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)

// Main pin output
#define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)
#define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)

// Define pull-ups and set high at the main pin
#define PIN_DATA_SET PORTB |= (1 << PB0)


// Define pull-ups set down at the main pin
#define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)
#define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)

// Read the main pins
#define PIN_SQCK_READ (PIND & (1 << PIND6))
#define PIN_SUBQ_READ (PIND & (1 << PIND7))
#define PIN_WFCK_READ (PINB & (1 << PINB1))

// Handling and use of the LED pin
#define LED_RUN
#define PIN_LED_OUTPUT DDRB |= (1 << DDB5)
#define PIN_LED_ON PORTB |= (1 << PB5)
#define PIN_LED_OFF PORTB &= ~(1 << PB5)

// Handling the BIOS patch

// BIOS interrupt seting
#define TIMER_INTERRUPT_ENABLE TIMSK0 |= (1 << OCIE0A)
#define TIMER_INTERRUPT_DISABLE TIMSK0 &= ~(1 << OCIE0A)

// BIOS timer clear
#define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

// Pins input
#define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
#define PIN_AY_INPUT DDRD &= ~(1 << DDD3)
#define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
// Pin output
#define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
// Define pull-ups set high
#define PIN_DX_SET PORTD |= (1 << PD4)
// Define pull-ups set down
#define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
// Read pins for BIOS patch
#define PIN_AX_READ (PIND & (1 << PIND2))
#define PIN_AY_READ (PIND & (1 << PIND3))

// Handling the external interrupt
#define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT0)
#define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT1)

#define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)
#define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)

#define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)
#define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)

#define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))
#define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))

#define PIN_AX_INTERRUPT_VECTOR INT0_vect
#define PIN_AY_INTERRUPT_VECTOR INT1_vect

// Handling and reading the switch pin for patch BIOS
#define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)
#define PIN_SWITCH_SET PORTD |= (1 << PD5)
#define PIN_SWITCH_READ (PIND & (1 << PIND5))

#endif

