// *****************************************************************************************************************
// Configuration for different microcontrollers (MUC) to ensure compatibility with the code:
// - Defines the clock speed, timers, and interrupts for each MUC.
// - Configures I/O pins for data, clocks, and switches according to the requirements.
// - Enables pull-up resistors on input pins where needed.
// - Manages external interrupts and LED outputs for system feedback.
// - Ensures the setup is compatible with various microcontroller models (e.g., ATmega328, ATtiny series, etc.)
// *****************************************************************************************************************

//******************************************************************************************************************
// Configuring the clock speed and associated registers. The formula for calculating 
// the clock frequency is F_CPU / (TCCR0B |= (1<<CS00)) * (OCR0A = 159 +1) = 16000000 / (0 * (160)) = 100KHz
//******************************************************************************************************************

//******************************************************************************************************************

// Example: DDRB &= ~(1<<DDB0);

// Define the pins as inputs.

// Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), and then inverting it.
// The bitwise AND operation (&=) updates the register DDRB by clearing the DDB0 bit (setting it to 0) 
// without affecting the other bits. 
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask 
// (1<<DDB0) = b00000001, and then inverts it, which results in b11111110. The AND operation with DDRB clears DDB0.
// 
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    ~(b00000001) = b11111110  // Mask generated by shifting and inverting the bit
// After:   DDRB = b11111110  // The DDB0 bit is cleared (set to 0), while other bits remain unchanged
//******************************************************************************************************************

//******************************************************************************************************************

// Example: DDRB |= (1<<DDB0);

// Enable pull-ups and set high on the pins.

// Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), 
// and then apply a bitwise OR operation to set DDB0 to 1 (configure pin PB0 as an output).
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask 
// (1<<DDB0) = b00000001. The OR operation with DDRB sets the DDB0 bit to 1, leaving other bits unchanged.
// 
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    (1<<DDB0) = b00000001  // Mask generated by shifting the bit 1 to the left to position DDB0
// After:   DDRB = b11111111  // The DDB0 bit is set to 1, configuring pin PB0 as an output
//******************************************************************************************************************

//******************************************************************************************************************

// Example: (!!(PIND & (1<<PIND6)));

// Read the state of the input pins with Boolean Normalization.

// Create a mask by shifting the bit 1 to the left by PIND6's position (bit 6),
// then apply a bitwise AND operation to read the state of the PIND6 pin.
// Finally, apply a double logical NOT (!!) to normalize the result to 0 or 1.
// The result will be 1 (true) if the PIND6 pin is high (1), and 0 (false) if the PIND6 pin is low (0).
//
// For instance, if PIND = b01000000 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PIND6) = b01000000. The AND operation isolates the bit, and !! converts it to a pure boolean 1.
//
// Before: PIND = b01000000 // Initial value (PIN 6 is HIGH)
// Mask: (1<<PIND6) = b01000000 // Mask for bit 6
// Step 1: PIND & Mask = b01000000 (Value: 64)
// Step 2: !64 = 0
// Step 3: !0 = 1 // Final Normalized Result
// 
//******************************************************************************************************************

//******************************************************************************************************************

// Example: PORTB |= (1<<PB0);

// Set the state of an output pin to HIGH (Equivalent of Arduino digitalWrite(8, HIGH);).

// Create a mask by shifting the bit 1 to the left by PB0's position (bit 0),
// and then apply a bitwise OR operation to force the PB0 pin to a high state.
// This operation modifies only the target bit without affecting the others in the register.
//
// For instance, if PORTB = b10101010 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PB0) = b00000001. The OR operation between PORTB and the mask ensures the 0th bit becomes 1 (high).
//
// Before: PORTB = b10101010 // Initial value of PORTB (register controlling output pin states)
// Mask: (1<<PB0) = b00000001 // Mask generated by shifting the bit 1 to the left to position PB0
// Operation: PORTB | b00000001 = b10101011 // The 0th bit is set to 1 (high)
//
//******************************************************************************************************************

//******************************************************************************************************************

// Example: PORTB &= ~(1<<PB0);

// Set the state of an output pin to LOW (Equivalent of Arduino digitalWrite(8, LOW);).

// Create a mask by shifting the bit 1 to the left by PB0's position (bit 0).
// The mask is then inverted at the bit level (binary NOT) to create a clearing mask (all bits are 1 except the target bit, which is 0).
// Finally, a bitwise AND operation is applied to force the PB0 pin to a low state.
// This operation modifies only the target bit without affecting the others in the register.
//
// For instance, if PORTB = b10101011 (binary value), the generated mask is (1<<PB0) = b00000001.
// Inverting (NOT) the mask yields ~(1<<PB0) = b11111110.
// The bitwise AND operation between PORTB and the clearing mask ensures the 0th bit becomes 0 (low).
//
// Before: PORTB = b10101011 // Initial value of PORTB (register controlling output pin states)
// Mask: ~(1<<PB0) = b11111110 // Generated clearing mask
// Operation: PORTB & b11111110 = b10101010 // The 0th bit is set to 0 (low)
//
//******************************************************************************************************************

//******************************************************************************************************************

// Enables (masks in) the Hardware External Interrupt 0 (INT0).

// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, CHANGE);
//
// Example: EIMSK |= (1<<INT0);
//
// Creates a mask by shifting the bit 1 to the left to the position of the INT0 bit.
// A bitwise OR operation is then applied to the EIMSK (External Interrupt Mask Register) register to set that specific bit to 1.
// Enabling this bit tells the microcontroller to start listening for signals on the physical pin associated with INT0 (typically Pin D2 on the Arduino UNO/Nano).
//
// For instance, if EIMSK = b00000000 (all interrupts disabled), the generated mask is (1<<INT0) = b00000001 (assuming INT0 is defined as 0).
// The bitwise OR operation ensures the INT0 bit is set to 1, without affecting the other interrupts.
//
// Before: EIMSK = b00000000 // All interrupts disabled
// Mask: (1<<INT0) = b00000001 // Generated enable mask
// Operation: EIMSK | b00000001 = b00000001 // The INT0 interrupt is now enabled
//
//******************************************************************************************************************

//******************************************************************************************************************

// Disables (masks out) the Hardware External Interrupt 0 (INT0).

// Equivalent to the Arduino function: detachInterrupt(digitalPinToInterrupt(2));
//
// Example: EIMSK &= ~(1<<INT0);
//
// Creates a mask by shifting the bit 1 to the left by the position of the INT0 bit.
// The mask is then inverted at the bit level (binary NOT) to create a clearing mask (all bits are 1 except the target bit, which is 0).
// A bitwise AND operation is applied to the EIMSK (External Interrupt Mask Register) register to force that specific bit to 0.
// Disabling this bit tells the microcontroller to stop listening for signals on the physical pin associated with INT0 (typically Pin D2 on the Arduino UNO/Nano).
//
// For instance, if EIMSK = b00000001 (INT0 interrupt is enabled), the generated mask is (1<<INT0) = b00000001.
// Inverting (NOT) the mask yields ~(1<<INT0) = b11111110.
// The bitwise AND operation between EIMSK and the clearing mask ensures the INT0 bit becomes 0 (disabled).
//
// Before: EIMSK = b00000001 // INT0 interrupt is enabled
// Mask: ~(1<<INT0) = b11111110 // Generated disable mask
// Operation: EIMSK & b11111110 = b00000000 // The INT0 interrupt is now disabled
//
//******************************************************************************************************************

//******************************************************************************************************************

// Configures the external interrupt 0 (INT0) to trigger on a RISING edge (when the signal goes from LOW to HIGH).

// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, RISING);
//
// Example: EICRA |= (1<<ISC01)|(1<<ISC00);
//
// This operation sets both the ISC01 and ISC00 bits within the EICRA register (External Interrupt Control Register A) to 1.
// These two bits together form a 2-bit control field that determines how the INT0 pin should react to changes in voltage.
// The specific combination of ISC01=1 and ISC00=1 defines the "RISING Edge" mode according to the AVR datasheet.
//
// EICRA register (simplified view of relevant bits):
// | Bit 7 | Bit 6 | Bit 5 | Bit 4 | Bit 3 | Bit 2 | Bit 1 (ISC01) | Bit 0 (ISC00) |
// | :---: | :---: | :---: | :---: | :---: | :---: | :-----------: | :-----------: |
// | | | | | | | 1 | 1 |
//
// The bitwise OR (|=) ensures that only these two specific bits are modified, leaving all other interrupt configurations unchanged.
//
// Before: EICRA = b00000000 // Default state (usually LOW level triggers)
// Mask: (1<<ISC01)|(1<<ISC00) = b00000011 // Mask to set both bits 0 and 1
// Operation: EICRA | b00000011 = b00000011 // INT0 is now configured for RISING edge triggers
//
//******************************************************************************************************************

//******************************************************************************************************************

// Configures the external interrupt 0 (INT0) to trigger on a FALLING edge (when the signal goes from HIGH to LOW).
// Equivalent to the Arduino function: attachInterrupt(digitalPinToInterrupt(2), myFunctionName, FALLING);
//
// Example: (EICRA = (EICRA & ~(1<<ISC00)) | (1<<ISC01));
//
// This combined operation first ensures that the ISC00 bit is cleared to 0 (& ~(1<<ISC00)), and then sets the ISC01 bit to 1 (| (1<<ISC01)).
// These two bits together form a 2-bit control field that determines how the INT0 pin should react to changes in voltage.
// The specific combination of ISC01=1 and ISC00=0 defines the "FALLING Edge" mode according to the AVR datasheet.
//
// EICRA register (simplified view of relevant bits):
// | Bit 7 | Bit 6 | Bit 5 | Bit 4 | Bit 3 | Bit 2 | Bit 1 (ISC01) | Bit 0 (ISC00) |
// | :---: | :---: | :---: | :---: | :---: | :---: | :-----------: | :-----------: |
// | | | | | | | 1 | 0 |
//
// The complex bitwise operation ensures that we set a specific 2-bit value while leaving other unrelated bits in the EICRA register unchanged.
//
// Operation Breakdown:
// 1. Clear ISC00 bit: EICRA & ~(1<<ISC00)
// 2. Set ISC01 bit: ... | (1<<ISC01)
// Before:  EICRA = b00000011  // Initial value with ISC01 = 1 and ISC00 = 1 (rising edge trigger for INT0)
// Operation: EICRA & ~(1<<ISC00) clears ISC00 bit (sets it to 0) while keeping ISC01 at 1. Then OR operation with (1<<ISC01) ensures ISC01 stays 1.
// After:   EICRA = b00000010  // The bit ISC00 is now cleared, configuring INT0 to trigger on the falling edge.
//
//******************************************************************************************************************

//******************************************************************************************************************
// Identifier for the Interrupt Vector for External Interrupt 0 (INT0).
//
// Example: ISR(INT0_vect) { ... }
//
// This is not an executable instruction but a symbolic name (an alias or macro) defined in the AVR-GCC header files
// (<avr/interrupt.h>). It points to the specific memory address in the microcontroller's flash memory where the
// Interrupt Service Routine (ISR) for the INT0 event must reside.
//
// When you write ISR(INT0_vect) { ... }, you are telling the compiler: "Place this block of code at the
// location the CPU jumps to when a hardware signal is detected on the INT0 pin."
//
// In Arduino code, this identifier is hidden from the user and managed internally by the
// attachInterrupt() function.
//
//******************************************************************************************************************

#pragma once

#ifdef ATmega328_168

  static inline void optimizePeripherals(void) {
    // 1. Disable Interrupts during setup
    cli();

    // 2. Analog Modules Shutdown (Critical for Power)
    ADCSRA &= ~(1 << ADEN); // Disable ADC
    ACSR   |= (1 << ACD);   // Disable Analog Comparator

    // 3. Digital Input Disable (Set bits to 1 to DISABLE)
    // Disconnects digital buffers on analog pins to stop leakage
    DIDR0 = 0x3F; // Pins A0 to A5

    // 4. GPIO Strategy (Unused pins to Pull-up)
    // PORTx = 0xFF (Pull-ups) | DDRx = 0x00 (Inputs)
    PORTC |= 0xFF;

    // 5. Power Reduction Register (PRR)
    // We KEEP PRUSART0 (UART) and shut down EVERYTHING else.
    // _delay_ms() will still work (it's cycle-based, not timer-based).
    PRR = (1 << PRTWI)  | // I2C Off
          (1 << PRSPI)  | // SPI Off
          (1 << PRTIM0) | // Timer 0 Off (millis/delay Arduino Off)
          (1 << PRTIM1) | // Timer 1 Off
          (1 << PRTIM2) | // Timer 2 Off
          (1 << PRADC);   // ADC Clock Off

    // 6. Double Security for Timer 0
    TCCR0B = 0;
    TIMSK0 = 0;

    // 7. Restart interrupts if UART uses them (RX/TX ISR)
    sei();
  }

  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Main pin configuration

  // Define the main pins as inputs
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)  // Set DDRB register to configure PINB0 as input
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)  // Set DDRB register to configure PINB1 as input
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)  // Set DDRB register to configure PINB6 as input
  #define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)  // Set DDRB register to configure PINB7 as input

  // Enable pull-ups and set high on the main pins
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)  // Set DDRB register to configure PINB0 as output
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)  // Set DDRB register to configure PINB1 as output

  // Define pull-ups and set high at the main pin
  #define PIN_DATA_SET PORTB |= (1 << PB0)  // Set PORTB register to make PINB0 high (enable pull-up)

  // Clear the main pins (set low)
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)  // Set PORTB register to make PINB0 low
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)  // Set PORTB register to make PINB1 low

  // Read the state of the main input pins
  #define PIN_SQCK_READ (!!(PIND & (1 << PIND6)))  // Check if the value of PIND6 is high (1)
  #define PIN_SUBQ_READ (!!(PIND & (1 << PIND7)))  // Check if the value of PIND7 is high (1)
  #define PIN_WFCK_READ (!!(PINB & (1 << PINB1)))  // Check if the value of PIND1 is high (1)

  // LED pin handling (for indication)
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB |= (1 << DDB5)  // Configure PINB5 as output (for LED)
    #define PIN_LED_ON    PORTB |= (1 << PB5)  // Set PINB5 high (turn on LED)
    #define PIN_LED_OFF   PORTB &= ~(1 << PB5)  // Set PINB5 low (turn off LED)
  #endif

  // Handling the BIOS patch
  #if defined(SCPH_102) || defined(SCPH_100) || defined(SCPH_7500_9000) || defined(SCPH_7000) || defined(SCPH_5000_5500) || defined(SCPH_3500) || defined(SCPH_3000) || defined(SCPH_1000)

    // Define input pins for the BIOS patch
    #define PIN_AX_INPUT DDRD &= ~(1 << DDD2)  // Set DDRD register to configure PIND2 as input
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)  // Set DDRD register to configure PIND4 as input

    // Define output pins for the BIOS patch
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)  // Set DDRD register to configure PIND4 as output

    // Set pull-ups high on output pins
    #define PIN_DX_SET PORTD |= (1 << PD4)  // Set PORTD register to make PIND4 high

    // Set pull-ups low on output pins
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)  // Set PORTD register to make PIND4 low


    #define WAIT_AX_RISING    (!(PIND & (1 << PIND2)))  // Attend le début de l'impulsion
    #define WAIT_AX_FALLING   (PIND & (1 << PIND2))     // Attend la fin de l'impulsion

    // Read the input pins for the BIOS patch
    #define PIN_AX_READ (!!(PIND & (1 << PIND2)))  // Read the state of PIND2

    // Defin PIN_AY for HIGH_PATCH
    #if defined(SCPH_3000) || defined(SCPH_1000)
      #define PIN_AY_INPUT DDRD &= ~(1 << DDD3)  // Set DDRD register to configure PIND3 as input
      #define WAIT_AY_RISING     (!(PIND & (1 << PIND3))) // AY est sur PIND3
      #define WAIT_AY_FALLING    (PIND & (1 << PIND3))
 
    #endif
      // Handle switch input for BIOS patch
    #if defined(SCPH_7000)
      #define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)  // Configure PIND5 as input for switch
      #define PIN_SWITCH_SET PORTD |= (1 << PD5)     // Set PIND5 high (enable pull-up)
      #define PIN_SWITCH_READ (!!(PIND & (1 << PIND5)))  // Read the state of PIND5 (switch input)
    #endif

  #endif

  // #if defined(PSNEE_DEBUG_SERIAL_MONITOR)
  //   #define DEBUG_PRINT(x)     Serial.print(x)
  //   #define DEBUG_PRINTHEX(x)  Serial.print(x, HEX)
  //   #define DEBUG_PRINTLN(x)   Serial.println(x)
  //   #define DEBUG_FLUSH        Serial.flush()
  // #endif

#endif


#ifdef ATmega32U4_16U4

  static inline void optimizePeripherals(void) {
    // --- Digital Input Configuration (A0-A5) ---
    // On 32U4, A0-A5 are spread across Port F (F7-F4) and Port D (D4, D7)
    // 1. Set all Analog/Digital pins to Input
    DDRF &= ~((1<<DDF7)|(1<<DDF6)|(1<<DDF5)|(1<<DDF4)); // A0-A3
    DDRD &= ~((1<<DDD4)|(1<<DDD7));                    // A4-A5
    
    // 2. Disable Digital Input Buffers (DIDR0/DIDR2)
    // On 32U4, DIDR0 and DIDR2 control the digital buffer for ADC pins.
    // Setting these bits to 0 ENABLES digital reads (PINF/PIND).
    DIDR0 &= ~((1<<ADC7D)|(1<<ADC6D)|(1<<ADC5D)|(1<<ADC4D)); // A0-A3
    DIDR2 &= ~((1<<ADC10D)|(1<<ADC8D));                      // A4-A5

    // --- Analog Modules Shutdown (32U4 specific) ---
    // 1. Disable the ADC module
    ADCSRA &= ~(1 << ADEN);
    // 2. Disable the Analog Comparator
    ACSR   |= (1 << ACD);

    // --- Power Reduction Register (32U4 Hard Clock Shut Off) ---
    // PRR0 and PRR1 handle the clocks on 32U4.
    // Note: We DO NOT touch PRUSB if we want to keep the Serial/USB alive.
    PRR0 |= (1 << PRADC) | (1 << PRTIM0) | (1 << PRTIM1); 
    PRR1 |= (1 << PRTIM3); // 32U4 has an extra Timer 3

    // --- Timer 0 Specific Shutdown ---
    TCCR0B = 0;
    TIMSK0 = 0;    
  }

  //#define F_CPU 16000000L


  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Globale interrupt seting
  #define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
  #define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)



  // Handling the main pins

  // Main pins
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB4)
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB5)
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD7)
  #define PIN_SUBQ_INPUT DDRE &= ~(1 << DDE6)

  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB4)
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB5)

  // Define pull-ups and set high at the main pin
  #define PIN_DATA_SET PORTB |= (1 << PB4)
  // Define pull-ups set down at the main pin
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB4)
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB5)
  // Read the main pins
  #define PIN_SQCK_READ (PIND & (1 << PIND7))
  #define PIN_SUBQ_READ (PINE & (1 << PINE6))
  #define PIN_WFCK_READ (PINB & (1 << PINB5))

  // Handling and use of the LED pin
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB |= (1 << DDB6)
    #define PIN_LED_ON PORTB |= (1 << PB6)
    #define PIN_LED_OFF PORTB &= ~(1 << PB6)
  #endif

  // Handling the BIOS patch
  #if defined(SCPH_102) || defined(SCPH_102_legacy) || defined(SCPH_100) || defined(SCPH_7000_9000) || defined(SCPH_5500) || defined(SCPH_3500_5000) || defined(SCPH_3000) || defined(SCPH_1000)
  // Pins input
    #define PIN_AX_INPUT DDRD &= ~(1 << DDD1)
    #define PIN_AY_INPUT DDRD &= ~(1 << DDD0)
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
    // Pin output
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
    // Define pull-ups set high
    #define PIN_DX_SET PORTD |= (1 << PD4)
    // Define pull-ups set down
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
    // Read pins for BIOS patch
    #define PIN_AX_READ (PIND & (1 << PIND1))
    #define PIN_AY_READ (PIND & (1 << PIND0))
    // Handling and reading the switch pin for patch BIOS
    #ifdef PATCH_SWITCH
      #define PIN_SWITCH_INPUT DDRC &= ~(1 << DDC6)
      #define PIN_SWITCH_SET PORTC |= (1 << PC6)
      #define PIN_SWITCH_READ (PINC & (1 << PINC6))
    #endif

    // BIOS timer clear
    #define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

    // Handling the external interrupt
    #define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT1)
    #define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT0)

    #define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)
    #define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)

    #define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)
    #define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)

    #define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))
    #define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))

    #define PIN_AX_INTERRUPT_VECTOR INT1_vect
    #define PIN_AY_INTERRUPT_VECTOR INT0_vect

  #endif

#endif

#ifdef ATtiny85_45_25

static inline void optimizePeripherals(void) {
      // --- Analog Modules Shutdown (ATtiny Specific) ---
    // 1. Disable the ADC module
    ADCSRA &= ~(1 << ADEN);
    // 2. Disable the Analog Comparator
    ACSR |= (1 << ACD);

    // --- Power Reduction Register (Hard Clock Shut Off) ---
    // On ATtiny85, PRR controls Timer 0, Timer 1, USI, and ADC.
    // We stop the ADC and Timer 0 clocks.
    PRR |= (1 << PRADC) | (1 << PRTIM0);

    // --- Timer 0 Specific Shutdown ---
    TCCR0B = 0;
    TIMSK  = 0; // On ATtiny85, it's TIMSK (not TIMSK0)
}

  #define DF_CPU 8000000L
  #define TIMER_TCNT_CLEAR TCNT0 = 0x00;
  #define SET_OCROA_DIV OCR0A = 79;  //OCR0A – Output Compare Register A,100KHz
  #define SET_TIMER_TCCROA TCCR0A |= (1 << WGM01);
  #define SET_TIMER_TCCROB TCCR0B |= (1 << CS00);
  #define CTC_TIMER_VECTOR TIMER0_COMPA_vect



  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Globale interrupt seting
  #define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
  #define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)

  // Handling the main pins

  // Main pins input
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB2)
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB4)
  #define PIN_SQCK_INPUT DDRB &= ~(1 << DDB0)
  #define PIN_SUBQ_INPUT DDRB &= ~(1 << DDB1)

  // Main pin output
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB2)
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB4)

  // Define pull-ups and set high at the main pin
  #define PIN_DATA_SET PORTB |= (1 << PB2)

  // Define pull-ups set down at the main pin
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB2)
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB4)

  // Read the main pins
  #define PIN_SQCK_READ (PINB & (1 << PINB0))
  #define PIN_SUBQ_READ (PINB & (1 << PINB1))
  #define PIN_WFCK_READ (PINB & (1 << PINB4))

  #define TIMER_INTERRUPT_ENABLE TIMSK |= (1 << OCIE0A)
  #define TIMER_INTERRUPT_DISABLE TIMSK &= ~(1 << OCIE0A)

  // Handling and use of the LED pin
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB |= (1 << DDB3)
    #define PIN_LED_ON PORTB |= (1 << PB3)
    #define PIN_LED_OFF PORTB &= ~(1 << PB3)
  #endif

  #if defined(SCPH_1000) || defined(SCPH_3000) || defined(SCPH_3500_5000) || defined(SCPH_5500) || defined(SCPH_7000_9000) || defined(SCPH_100) || defined(SCPH_102_legacy) || defined(SCPH_102) 
   #error "ATtiny85_45_25 Not compatible with BIOS patch"
  #endif

  #if defined(PSNEE_DEBUG_SERIAL_MONITOR)
    #include <SoftwareSerial.h>
    SoftwareSerial mySerial(-1, 3); // RX, TX. (RX -1 = off)
    #define PIN_TXD_OUTPUT DDRB |= (1 << DDB3)
    // #define DEBUG_PRINT(x)     mySerial.print(x)
    // #define DEBUG_PRINTHEX(x)  mySerial.print(x, HEX)
    // #define DEBUG_PRINTLN(x)   mySerial.println(x)
    // #define DEBUG_FLUSH        mySerial.flush()
  #endif

#endif

// *****************************************************************************************************************
// WARNING:
// The following code  is not functional as-is.
// *****************************************************************************************************************


#ifdef ATtiny88_48

  #define F_CPU 16000000L
  #define TIMER_TCNT_CLEAR TCNT0 = 0x00            //TCNT0 - Timer/Counter Register
  #define SET_OCROA_DIV OCR0A = 159;               //OCR0A – Output Compare Register A, 0x10011111, 100KHz
  #define SET_TIMER_TCCROA TCCR0A |= (1 << CTC0);  //TCCR0A – Timer/Counter Control Register A. turn on CTC mode, CTC0
  // On ATtiny88, TCCR0B doesn't exist — clock select bits (CS01, CS00) are in TCCR0A.
  // This sets the prescaler to 1, so the timer runs at full system clock (16 MHz).
  #define SET_TIMER_TCCROB TCCR0A |= (1 << CS01) | (1 << CS00)

  #define CTC_TIMER_VECTOR TIMER0_COMPA_vect  //interrupt vector for match event, OCR0A comparison and Timer/Counter 0


  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>

  // Globale interrupt seting
  #define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
  #define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)

  // Handling the main pins

  // Main pins input
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0
  #define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)

  // Main pin output
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)  // Create a mask (1<<0) with the first bit at 1 b00000001,
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)  // |= updates the DDRB register with the OR operator and the mask, DDRB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

  // Define pull-ups and set high at the main pin
  #define PIN_DATA_SET PORTB |= (1 << PB0)  // Create a mask (1<<0) with the first bit at 1 b00000001, 
                                            // |= updates the PORTB register with the OR operator and the mask, PORTB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

  // Define pull-ups set down at the main pin
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0

  // Read the main pins
  #define PIN_SQCK_READ (PIND & (1 << PIND6))  // Create a mask (1<<6) with the six bit at 1 b00100000,
  #define PIN_SUBQ_READ (PIND & (1 << PIND7))  // compare the PINB register and the mask with the AND operator, and returns the result, PINB bxx1xxxxx AND mask b00100000 = 1
  #define PIN_WFCK_READ (PINB & (1 << PINB1))

  // Handling and use of the LED pin
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRD |= (1 << DDD0)
    #define PIN_LED_ON PORTD |= (1 << PD0)
    #define PIN_LED_OFF PORTD &= ~(1 << PD0)
  #endif

  // Handling the BIOS patch
  #if defined(SCPH_102) || defined(SCPH_100) || defined(SCPH_7000_9000) || defined(SCPH_5500) || defined(SCPH_3500_5000) || defined(SCPH_3000) || defined(SCPH_1000)
    // BIOS interrupt seting
    #define TIMER_INTERRUPT_ENABLE TIMSK0 |= (1 << OCIE0A)
    #define TIMER_INTERRUPT_DISABLE TIMSK0 &= ~(1 << OCIE0A)

    // BIOS timer clear
    #define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

    // Pins input
    #define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
    #define PIN_AY_INPUT DDRD &= ~(1 << DDD3)
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
    // Pin output
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
    // Define pull-ups set high
    #define PIN_DX_SET PORTD |= (1 << PD4)
    // Define pull-ups set down
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
    // Read pins for BIOS patch
    #define PIN_AX_READ (PIND & (1 << PIND2))
    #define PIN_AY_READ (PIND & (1 << PIND3))

    // Handling the external interrupt
    #define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT0)
    #define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT1)

    #define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)
    #define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)

    #define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)
    #define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)

    #define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))
    #define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))

    #define PIN_AX_INTERRUPT_VECTOR INT0_vect
    #define PIN_AY_INTERRUPT_VECTOR INT1_vect

    // Handling and reading the switch pin for patch BIOS
    #ifdef PATCH_SWITCH
      #define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)
      #define PIN_SWITCH_SET PORTD |= (1 << PD5)
      #define PIN_SWITCH_READ (PIND & (1 << PIND5))
    #endif
  #endif

#endif

#ifdef ATtiny214_414

//#define SET_CTRLA
#define DF_CPU 20000000L
#define TIMER_TCNT_CLEAR TCA0.SINGLE.CNT = 0x00                           //TCNT0 - Timer/Counter Register
#define SET_OCROA_DIV TCA0.SINGLE.CMP0L = 100;                            //OCR0A – Output Compare Register A, 0x10011111, 100KHz
#define SET_TIMER_TCCROA TCA0.SINGLE.CTRLB |= (1 << TCA_SINGLE_WGM0);     //TCA_SINGLE_WGMODE_FRQ_gc    //TCCR0A – Timer/Counter Control Register A. turn on CTC mode, CTC0
#define SET_TIMER_TCCROB TCA0.SINGLE.CTRLA |= (1 << TCA_SINGLE_CLKSEL0);  //TCA_SINGLE_CLKSEL_DIV1_gc//TCCR0B – Timer/Counter Control Register B,  CS00: Clock Select,  clk I/O
                                                                          //Waveform Generation Mode, Mode 2 CTC
#define CTC_TIMER_VECTOR TCA0_OVF_vect                                    //TCA0_CMP0_vect            //interrupt vector for match event, OCR0A comparison and Timer/Counter 0


#include <stdint.h>
#include <stdbool.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/sfr_defs.h>
#include <util/delay.h>

// Globale interrupt seting
#define GLOBAL_INTERRUPT_ENABLE __asm__ __volatile__("sei" ::)   //CPU.SREG   |=  (1<<7)
#define GLOBAL_INTERRUPT_DISABLE __asm__ __volatile__("cli" ::)  //CPU.SREG   &= ~(1<<7)

// Handling the main pins

// Main pins input
#define PIN_DATA_INPUT PORTA.DIR = PIN2_bm
#define PIN_WFCK_INPUT PORTA.DIR = PIN1_bm  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
#define PIN_SQCK_INPUT PORTA.DIR = PIN4_bm  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0
#define PIN_SUBQ_INPUT PORTA.DIR = PIN3_bm

// Main pin output
#define PIN_DATA_OUTPUT PORTA.DIR |= PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001,
#define PIN_WFCK_OUTPUT PORTA.DIR |= PIN1_bm  // |= updates the DDRB register with the OR operator and the mask, DDRB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

// Define pull-ups and set high at the main pin
#define PIN_DATA_SET PORTA.OUT |= PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001,
                                           // |= updates the PORTB register with the OR operator and the mask, PORTB bxxxxxxxx OR mask b00000001 = bxxxxxxx1

// Define pull-ups set down at the main pin
#define PIN_DATA_CLEAR PORTA.OUT &= ~PIN2_bm  // Create a mask (1<<0) with the first bit at 1 b00000001 uses the ~ operator to perform a bit inversion b11111110,
#define PIN_WFCK_CLEAR PORTA.OUT &= ~PIN1_bm  // &= updates the DDRB register with the AND operator and the mask, DDRB bxxxxxxxx OR mask b11111110 = bxxxxxxx0

// Read the main pins
#define PIN_SQCK_READ PORTA.IN& PIN4_bm  // Create a mask (1<<6) with the six bit at 1 b00100000,
#define PIN_SUBQ_READ PORTA.IN& PIN3_bm  // compare the PINB register and the mask with the AND operator, and returns the result, PINB bxx1xxxxx AND mask b00100000 = 1
#define PIN_WFCK_READ PORTA.IN& PIN1_bm

// Handling and use of the LED pin
#define LED_RUN
#define PIN_LED_OUTPUT PORTB.DIR |= PIN2_bm
#define PIN_LED_ON PORTB.OUT |= PIN2_bm
#define PIN_LED_OFF PORTB.OUT &= ~PIN2_bm

// Handling the BIOS patch

// BIOS interrupt seting
#define TIMER_INTERRUPT_ENABLE TCA0.SPLIT.INTCTRL |= TCA_SINGLE_CMP0_bm
#define TIMER_INTERRUPT_DISABLE TCA0.SPLIT.INTCTRL &= ~TCA_SPLIT_HCMP0_bm

// BIOS timer clear
#define TIMER_TIFR_CLEAR TCA0.SPLIT.INTFLAGS = TCA_SPLIT_HCMP0_bm

// Pins input
#define PIN_AX_INPUT PORTB.DIR &= ~PIN3_bm
#define PIN_AY_INPUT PORTA.DIR &= ~PIN7_bm
#define PIN_DX_INPUT PORTA.DIR &= ~PIN6_bm
// Pin output
#define PIN_DX_OUTPUT PORTA.DIR |= PIN6_bm
// Define pull-ups set high
#define PIN_DX_SET PORTA.OUT |= PIN6_bm
// Define pull-ups set down
#define PIN_DX_CLEAR PORTA.OUT &= ~PIN6_bm
// Read pins for BIOS patch
#define PIN_AX_READ PORTB.IN& PIN3_bm
#define PIN_AY_READ PORTA.IN& PIN6_bm

// Handling the external interrupt
//#define PIN_AX_INTERRUPT_ENABLE     PORTB.PIN3CTRL  |=  (1<<INTn)
//#define PIN_AY_INTERRUPT_ENABLE     PORTA.PIN7CTRL  |=  (1<<INTn)

#define PIN_AX_INTERRUPT_DISABLE PORTB.PIN3CTRL = PORT_ISC_INTDISABLE_gc
#define PIN_AY_INTERRUPT_DISABLE PORTA.PIN7CTRL = PORT_ISC_INTDISABLE_gc

#define PIN_AX_INTERRUPT_RISING PORTB.PIN3CTRL = PORT_ISC_RISING_gc
#define PIN_AY_INTERRUPT_RISING PORTA.PIN7CTRL = PORT_ISC_RISING_gc

#define PIN_AX_INTERRUPT_FALLING PORTB.PIN3CTRL = PORT_ISC_FALLING_gc
#define PIN_AY_INTERRUPT_FALLING PORTA.PIN7CTRL = PORT_ISC_FALLING_gc

//#define PB3_INTERRUPT PORTB.INTFLAGS & PIN3_bm
//#define PA7_INTERRUPT PORTB.INTFLAGS & PIN7_bm

#define PIN_AX_INTERRUPT_VECTOR PORTB_PORT_vect
#define PIN_AY_INTERRUPT_VECTOR PORTA_PORT_vect

// Handling and reading the switch pin for patch BIOS
#define PIN_SWITCH_INPUT PORTA.DIR &= ~PIN5_bm
#define PIN_SWITCH_SET PORTA.OUT |= PIN5_bm
#define PIN_SWITCH_READ PORTA.IN& PIN5_bm

#endif

#ifdef LGT8F328P

#define F_CPU 32000000L


#include <stdint.h>
#include <stdbool.h>
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/sfr_defs.h>
#include <util/delay.h>

// Globale interrupt seting
#define GLOBAL_INTERRUPT_ENABLE SREG |= (1 << 7)
#define GLOBAL_INTERRUPT_DISABLE SREG &= ~(1 << 7)

// Handling the main pins

// Main pins input
#define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)
#define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)
#define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)
#define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)

// Main pin output
#define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)
#define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)

// Define pull-ups and set high at the main pin
#define PIN_DATA_SET PORTB |= (1 << PB0)


// Define pull-ups set down at the main pin
#define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)
#define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)

// Read the main pins
#define PIN_SQCK_READ (PIND & (1 << PIND6))
#define PIN_SUBQ_READ (PIND & (1 << PIND7))
#define PIN_WFCK_READ (PINB & (1 << PINB1))

// Handling and use of the LED pin
#define LED_RUN
#define PIN_LED_OUTPUT DDRB |= (1 << DDB5)
#define PIN_LED_ON PORTB |= (1 << PB5)
#define PIN_LED_OFF PORTB &= ~(1 << PB5)

// Handling the BIOS patch

// BIOS interrupt seting
#define TIMER_INTERRUPT_ENABLE TIMSK0 |= (1 << OCIE0A)
#define TIMER_INTERRUPT_DISABLE TIMSK0 &= ~(1 << OCIE0A)

// BIOS timer clear
#define TIMER_TIFR_CLEAR TIFR0 |= (1 << OCF0A)

// Pins input
#define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
#define PIN_AY_INPUT DDRD &= ~(1 << DDD3)
#define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
// Pin output
#define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
// Define pull-ups set high
#define PIN_DX_SET PORTD |= (1 << PD4)
// Define pull-ups set down
#define PIN_DX_CLEAR PORTD &= ~(1 << PD4)
// Read pins for BIOS patch
#define PIN_AX_READ (PIND & (1 << PIND2))
#define PIN_AY_READ (PIND & (1 << PIND3))

// Handling the external interrupt
#define PIN_AX_INTERRUPT_ENABLE EIMSK |= (1 << INT0)
#define PIN_AY_INTERRUPT_ENABLE EIMSK |= (1 << INT1)

#define PIN_AX_INTERRUPT_DISABLE EIMSK &= ~(1 << INT0)
#define PIN_AY_INTERRUPT_DISABLE EIMSK &= ~(1 << INT1)

#define PIN_AX_INTERRUPT_RISING EICRA |= (1 << ISC01) | (1 << ISC00)
#define PIN_AY_INTERRUPT_RISING EICRA |= (1 << ISC11) | (1 << ISC10)

#define PIN_AX_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC00)) | (1 << ISC01))
#define PIN_AY_INTERRUPT_FALLING (EICRA = (EICRA & ~(1 << ISC10)) | (1 << ISC11))

#define PIN_AX_INTERRUPT_VECTOR INT0_vect
#define PIN_AY_INTERRUPT_VECTOR INT1_vect

// Handling and reading the switch pin for patch BIOS
#define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)
#define PIN_SWITCH_SET PORTD |= (1 << PD5)
#define PIN_SWITCH_READ (PIND & (1 << PIND5))

#endif

#ifdef RP2040

  #include <stdint.h>
  #include <stdbool.h>
  #include <pico/stdlib.h>

  // Main pin configuration

  // Define the main pins as inputs
  #define RP2040_INPUT(gpio) (gpio_set_dir(gpio, false))
  #define PIN_DATA_INPUT RP2040_INPUT(4)    // Set GPIO4 as input
  #define PIN_WFCK_INPUT RP2040_INPUT(5)    // Set GPIO5 as input
  #define PIN_SQCK_INPUT RP2040_INPUT(6)    // Set GPIO6 as input
  #define PIN_SUBQ_INPUT RP2040_INPUT(7)    // Set GPIO7 as input
  
  // Enable pull-ups and set high on the main pins
  #define RP2040_OUTPUT(gpio) (gpio_set_dir(gpio, true))
  #define PIN_DATA_OUTPUT RP2040_OUTPUT(4)  // Set GPIO4 as output
  #define PIN_WFCK_OUTPUT RP2040_OUTPUT(5)  // Set GPIO5 as output
  
  // Define pull-ups and set high at the main pin
  #define RP2040_SET(gpio, high) (gpio_put(gpio, high))
  #define PIN_DATA_SET RP2040_SET(4, true)    // Set GPIO4 high
  
  // Clear the main pins (set low)
  #define PIN_DATA_CLEAR RP2040_SET(4, false) // Set GPIO4 low
  #define PIN_WFCK_CLEAR RP2040_SET(5, false) // Set GPIO5 low
  
  // Read the state of the main input pins
  #define RP2040_READ(gpio) (gpio_get(gpio))
  #define PIN_WFCK_READ RP2040_READ(5)  // Check if the value of GPIO5 is high (1)
  #define PIN_SQCK_READ RP2040_READ(6)  // Check if the value of GPIO6 is high (1)
  #define PIN_SUBQ_READ RP2040_READ(7)  // Check if the value of GPIO7 is high (1)

  // LED pin handling (for indication)
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT  RP2040_OUTPUT(25)  // Configure GPIO25 as output (builtin LED)
    #define PIN_LED_ON      RP2040_SET(25, true)  // Set GPIO25 high (turn on LED)
    #define PIN_LED_OFF     RP2040_SET(25, false)  // Set GPIO25 low (turn off LED)
  #endif

  // Handling the BIOS patch
  #if defined(SCPH_102) || defined(SCPH_100) || defined(SCPH_7500_9000) || defined(SCPH_7000) || defined(SCPH_5000_5500) || defined(SCPH_3500) || defined(SCPH_3000) || defined(SCPH_1000)

    // Define input pins for the BIOS patch
    #define PIN_AX_INPUT RP2040_INPUT(8)        // Set GPIO8 as input
    #define PIN_DX_INPUT RP2040_INPUT(9)        // Set GPIO9 as input

    // Define output pins for the BIOS patch
    #define PIN_DX_OUTPUT RP2040_OUTPUT(9)      // Set GPIO9 as output

    // Set pull-ups high on output pins
    #define PIN_DX_SET RP2040_SET(9, true)      // Set GPIO9 high

    // Set pull-ups low on output pins
    #define PIN_DX_CLEAR RP2040_SET(9, false)   // Set GPIO4 low


    #define WAIT_AX_RISING    (!RP2040_READ(8)) // Attend le début de l'impulsion
    #define WAIT_AX_FALLING    (RP2040_READ(8)) // Attend la fin de l'impulsion

    // Read the input pins for the BIOS patch
    #define PIN_AX_READ RP2040_READ(8)          // Check if the value of GPIO8 is high (1)

    // Defin PIN_AY for HIGH_PATCH
    #if defined(SCPH_3000) || defined(SCPH_1000)
      #define PIN_AY_INPUT RP2040_INPUT(10)        // Set GPIO10 as input
      #define WAIT_AY_RISING     (!RP2040_READ(10)) // AY est sur GPIO10
      #define WAIT_AY_FALLING    (RP2040_READ(10))
 
    #endif
      // Handle switch input for BIOS patch
    #if defined(SCPH_7000)
      #define PIN_SWITCH_INPUT RP2040_INPUT(11)        // Set GPIO11 as input
      #define PIN_SWITCH_SET RP2040_SET(11, true)      // Set GPIO11 high
      #define PIN_SWITCH_READ RP2040_READ(11)          // Check if the value of GPIO11 is high (1)
    #endif

  #endif

#endif